[package]
name = "zlist"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
byte-unit = "4"
chrono = "0.4"
prettytable-rs = "0.9.0"
thiserror = "1"
timeago = "0.3.1"
